- set_fact:
    nginx_conf: /usr/local/etc/nginx/
  when: ansible_distribution == 'FreeBSD'
- set_fact:
    nginx_conf: /etc/nginx/
  when: ansible_system == 'Linux'

- name: Create /var/www/
  file: path=/var/www/ state=directory
- name: Paste index.html
  template: src=index.html dest=/var/www/index.html

- name: Paste localhost vhost
  template: src=00_localhost dest={{ nginx_conf }}sites-enabled/00_localhost
  notify: reload nginx
